<?php

declare(strict_types=1);

/**
 * This file is part of the Nexus Assert library.
 *
 * (c) 2025 John Paul E. Balandan, CPA <paulbalandan@gmail.com>
 *
 * For the full copyright and license information, please view
 * the LICENSE file that was distributed with this source code.
 */

namespace Nexus\Assert\Tools;

use Nexus\Assert\Expectable;
use Nexus\Assert\Exporter;

/**
 * @internal
 */
final class ReadmeGenerator
{
    public const OUTPUT_PATH = __DIR__.'/../../README.md';
    private const DEFAULT_CONTEXT = ['value', 'type'];
    private const SPACE_AND_BACKTICKS_PADDING = 4;
    private const SPACE_PADDING = 2;
    private const TEMPLATE_PATH = __DIR__.'/../resources/README.md.tpl';

    public function generate(): string
    {
        $template = file_get_contents(self::TEMPLATE_PATH);

        if (false === $template) {
            throw new \RuntimeException('Failed to read the README template file.');
        }

        $reflection = new \ReflectionClass(Expectable::class);
        $methods = $reflection->getMethods(\ReflectionMethod::IS_PUBLIC);

        $exporter = new Exporter();
        $methodSignatures = array_combine(
            array_map(static fn(\ReflectionMethod $method): string => $method->getName(), $methods),
            array_map(static fn(\ReflectionMethod $method): string => \sprintf(
                '%s(%s): self',
                $method->getName(),
                implode(', ', array_map(static fn(\ReflectionParameter $param): string => \sprintf(
                    '%s%s%s%s$%s%s',
                    $param->hasType() && $param->allowsNull() ? '?' : '',
                    $param->hasType() ? self::typeAsString($param->getType()).' ' : '',
                    $param->isPassedByReference() ? '&' : '',
                    $param->isVariadic() ? '...' : '',
                    $param->getName(),
                    $param->isOptional() ? ' = '.$exporter->exportValue($param->getDefaultValue()) : '',
                ), $method->getParameters())),
            ), $methods),
        );

        $context = [];

        foreach (array_keys($methodSignatures) as $methodName) {
            if (\array_key_exists($methodName, ExpectationVariantsGenerator::NON_DEFAULT_CONTEXT)) {
                $context[$methodName] = ExpectationVariantsGenerator::NON_DEFAULT_CONTEXT[$methodName];
            } else {
                $context[$methodName] = self::DEFAULT_CONTEXT;
            }
        }

        $context = array_map(static fn(array $ctx): string => '`'.implode('`, `', $ctx).'`', $context);

        $data = <<<'MD'
            <!--
            This README.md file is auto-generated. Do not edit this file directly.

            To regenerate this file:
            1. Edit the template file located at "tools/resources/README.md.tpl".
            2. Modify the logic in "tools/src/ReadmeGenerator.php" as needed.
            3. Run the script: `php bin/generate-readme`
            -->


            MD;
        $data .= str_replace(
            '{{ EXPECTATION_METHODS_TABLE }}',
            self::generateTable($methodSignatures, $context),
            $template,
        );

        return $data;
    }

    private static function typeAsString(\ReflectionType $type): string
    {
        if ($type instanceof \ReflectionNamedType) {
            return $type->getName();
        }

        if (! $type instanceof \ReflectionUnionType && ! $type instanceof \ReflectionIntersectionType) {
            throw new \LogicException('Unsupported reflection type encountered.');
        }

        $separator = $type instanceof \ReflectionUnionType ? '\|' : '&';
        $types = array_map(self::typeAsString(...), $type->getTypes());
        sort($types);

        return implode($separator, $types);
    }

    /**
     * @param array<string, string> $methodSignatures
     * @param array<string, string> $context
     */
    private static function generateTable(array $methodSignatures, array $context): string
    {
        \assert([] !== $methodSignatures && [] !== $context);

        $maxSign = max(array_map(strlen(...), array_values($methodSignatures))) + self::SPACE_AND_BACKTICKS_PADDING;
        $maxContext = max(array_map(strlen(...), array_values($context))) + self::SPACE_PADDING;

        $table = \sprintf("| Methods%s | Available Context %s |\n", str_repeat(' ', $maxSign - 9), str_repeat(' ', $maxContext - 20));
        $table .= \sprintf("| %s | %s |\n", str_repeat('-', $maxSign - self::SPACE_PADDING), str_repeat('-', $maxContext - self::SPACE_PADDING));

        foreach ($methodSignatures as $name => $signature) {
            $table .= \sprintf(
                "| `%s`%s | %s%s |\n",
                $signature,
                str_repeat(' ', $maxSign - \strlen($signature) - self::SPACE_AND_BACKTICKS_PADDING),
                $context[$name],
                str_repeat(' ', $maxContext - \strlen($context[$name]) - self::SPACE_PADDING),
            );
        }

        return trim($table);
    }
}
