name: Static Code Analysis

on:
  schedule:
    - cron: '0 0 * * *'
  pull_request:
  push:
    branches:
      - 1.x
    paths:
      - '**.php'
      - .github/workflows/static-code-analysis.yml
      - tools/resources/README.md.tpl
      - composer.json
      - '**.neon'

concurrency:
  group: sca-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        php-version:
          - '8.2'
          - '8.3'
          - '8.4'
          - '8.5'

    name: Static Code Analysis
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 1
          persist-credentials: false

      - name: Setup PHP
        uses: shivammathur/setup-php@accd6127cb78bee3e8082180cb391013d204ef9f # 2.37.0
        with:
          php-version: ${{ matrix.php-version }}
          coverage: none
          ini-values: display_errors=On, display_startup_errors=On, error_reporting=-1, zend.assertions=1, assert.exception=1

      - name: Get composer cache directory
        id: cache-dir
        run: |
          echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_OUTPUT

      - name: Cache Composer dependencies
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5.0.4
        with:
          path: ${{ steps.cache-dir.outputs.COMPOSER_CACHE_DIR }}
          key: ${{ github.workflow }}-PHP_${{ matrix.php-version }}-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ github.workflow }}-PHP_${{ matrix.php-version }}-

      - name: Install dependencies
        run: |
          composer update --ansi

      - name: Check - PHP Configuration
        run: vendor/bin/phpunit --check-php-configuration

      - name: Check - PHP-CS-Fixer
        run: composer cs:check

      - name: Check - PHPStan
        run: composer phpstan:check

      - name: Check - Auto-review tests
        run: composer test:auto-review

      - name: Check - Static Type Analysis
        run: composer test:stan
